



# Cargar la librería argparse
library(argparse)

# Crear un nuevo objeto ArgumentParser
parser <- ArgumentParser(description = 'parseroooo!!')

parser$add_argument('-f', '--data.input', type='character', help='folders where files generated by OpenPose are')
parser$add_argument('-s', '--path.save', type='character', help='save here')
parser$add_argument('-p','--parquet', action='store_true', help='generate parquet file')
parser$add_argument('-a','--all.in.file', action='store_false', help='all data in one file')
parser$add_argument('--csv', action='store_true', help='Write csv file')


# Parsear los argumentos
args <- parser$parse_args()

### dfMaker ######

dfMaker<- function(input.folders,save.csv=F, output.folder,return.empty=F, extra.var,save.parquet=F, type.point="full") {
  
  
  input.folders<-list.dirs(input.folders, full.names=TRUE,recursive = F)
  
  
  videoMaker<<- function(input.folders,output.folder,save.csv,return.empty, extra.var,save.parquet) {
    
    
    
    if (save.parquet==TRUE) {
      
      ifelse(require(arrow),"arrow is alreday installed", install.packages("arrow")) 
    }
    
    files<-list.files(input.folders, pattern="*.json", full.names=TRUE)
    
    out=NULL
    emptyFrames=NULL
    
    
    
    frameMaker<<-function(file_name, extra.var){
      
      if (require(arrow)==TRUE) {
        rawData<-read_json_arrow(file_name,as_data_frame = T) #read file
        
        rawData<-rawData[[2]][[1]]  #extract lists
        
        dfPoints=NULL
        
        
        if(sum(capture.output(rawData)!="<unspecified> [0]")!=0) {
          for (id in 1:nrow(rawData)) {
            points<-data.frame(data=unlist(rawData[id,]),people=id)
            dfPoints=rbind(dfPoints,points) } 
        }else{
          empty<-paste(file_name)
        }
      }else{
        require(jsonlite)
        rawData<-read_json( path = file_name) #read file
        
        rawData<-rawData[2]  #extract lists
        rawData<-rawData[[1]]  #extract lists
        
        dfPoints=NULL
        for (id in 1:length(rawData)) {
          
          if(length(rawData)!=0) {
            points<-data.frame(unlist(rawData[[id]]),people=id)
            dfPoints=rbind(dfPoints,points) }else{
              empty<-paste(file_name)
            }}
      }
      
      ####################### Only pose vs. full #########################################
      
      if (type.point=="full") {
        pattern<- sample(T, size=137*3, replace= T) # points triplicates
        points<-c(0:24,0:69,0:20,0:20)
      }
      
      if (type.point=="pose") {
        pattern<- sample(T, size=25*3, replace= T) # points triplicates
        points<-c(0:24)
      }
      
      #####################################################################   
      
      pattern<-c(F,pattern)
      
      if(!is.null(dfPoints)){
        pattern<-rep(pattern, times=max(dfPoints$people))
      }  
      
      
      
      dfPoints<-dfPoints[pattern,]
      
      ### type
      
      type<-rownames(dfPoints)
      type<-gsub("_2d[0-9]*", "", type)
      
      
      ### frame
      
      regmatches(file_name,regexec( "[0-9]{12}", file_name))->frame # frame has 12 digits
      frame<-as.numeric(frame[[1]])
      
      
      ### name
      
      name<-gsub(paste("_[0-9]{12}.*", sep = ""),"", file_name)
      name<-gsub(paste(".*/",sep = ""), "", name)
      
      
      ###
      triplet<-c(T,F,F)
      ###    
      
      groups <- c("x", "y", "c") # the variables of the final df
      
      
      #############Extra variables###############        
      if (extra.var==TRUE) {
        
        ### words
        
        words<-gsub("_[0-9]{12}.*", "", file_name)
        words<-gsub(".*[0-9]_", "", words)
        
        ### name
        
        name<-gsub(paste("_[0-9]{12}.*", sep = ""),"", file_name)
        name<-gsub(paste(".*/",sep = ""), "", name)
        
        ### date
        
        date<-gsub(paste(".*/",sep = ""), "", file_name)
        date<-as.Date(gsub(paste("_.*",sep = ""), "", date))
        
        
        
        if(!is.null(dfPoints)){
          pointsDF<-data.frame(split(dfPoints[,1], f = groups), 
                               people=dfPoints$people[triplet],
                               typePoint=  type[triplet],
                               point= points,
                               words=words,
                               frame=frame,
                               name=name,
                               date=date) # split in 3 columns 
          return(pointsDF)
        }else{
          return(empty)
        }
      }else{
        if(!is.null(dfPoints)){
          pointsDF<-data.frame(split(dfPoints[,1], f = groups), 
                               people=dfPoints$people[triplet],
                               typePoint=  type[triplet],
                               point= points,
                               frame=frame,
                               name=name) # split in 3 columns 
          return(pointsDF)
        }else{
          return(empty)
        }}
      
      
    }
    
    
    for (i in 1:length(files)){
      
      c <- data.frame(frameMaker(files[i],extra.var = extra.var))
      
      if (length(c)!=1) {
        out=rbind(out,c)
      }else{
        
        emptyFrames=rbind(emptyFrames,c)
      }
      
      
      
    }
    
    if (save.csv==TRUE) {
      folder<-output.folder
      dir.create(folder,recursive = TRUE,showWarnings = FALSE)
      write.csv(x = out, paste(folder,"/",unique(out$name),".csv",sep = ""),row.names = F)
      
    }
    
    
    
    if (save.parquet==TRUE) {
      
      folder<-output.folder
      dir.create(folder,recursive = TRUE,showWarnings = FALSE)
      write_parquet(x = out, sink = paste(folder,"/",unique(out$name),".parquet",sep = ""))
    }
    
    if (return.empty==T) {
      video<-list(out,emptyFrames)
      return(video)
    }else{
      return(out)
    }
    
    
    
    
  }
  
  
  
  result=NULL
  dFinal<-NULL
  totalEmpty<-NULL
  
  for (i in 1:(length(input.folders))) {
    
    
    dfVideo<-videoMaker( input.folders[i],save.csv = save.csv,output.folder = output.folder,return.empty = return.empty, extra.var = extra.var,save.parquet = save.parquet)
    
    if (return.empty==F) {
      
      result=rbind(result,dfVideo)
    }else{
      
      dFinal=rbind(dFinal,dfVideo[[1]])
      totalEmpty=rbind(totalEmpty,dfVideo[[2]])
      result<-list(dFinal,totalEmpty)
      
    }
    
    
  }
  
  return(result)
}

  
  
  




###### cramerOpenPose##############

cramerOpenPosev2 <- function(df,set.NAs, type.point = "pose_keypoints", fixed.point.x = 1, fixed.point.y = 1, v.i=5, save.parquet, save.by.video=TRUE,path.to.save, save.csv=FALSE) {

  
  ##### transform 0 values to NAs values ###############
  
  if ( set.NAs == TRUE ) {
    
    df$x[ df$x == 0 ] <- NA
    
    df$y[ df$y == 0 ] <- NA
  }
  
  
  # set automatic fix parameters ######  
  
  total_frames<- ( nrow( df ) / 137 ) -1 ### number of frames in data frame :P
  
  total_matrix = NULL  
  
  
  ############## the process frame by frame ##############
  
  for ( frame_number in 0:total_frames ) {
    
    first_element<- 137 * frame_number + 1 
    # frame number is refered inside the data set 
    # and it is independent of the number frame in the video
    
    frame_df<- ( df[ first_element:( first_element + 136 ) , ] )
    
    new_x_values<- frame_df$x - frame_df[ frame_df$point == fixed.point.x & frame_df$typePoint == type.point , "x" ]
    new_y_values<- ( frame_df$y - frame_df[ frame_df$point == fixed.point.y & frame_df$typePoint == type.point , "y" ]) * (-1)
    
    
    ##### preapring cramer #########
    
    m<- matrix( cbind( new_x_values , new_y_values ) , ncol = 2 ) # matrix
    i<- m[ v.i + 1 , ]
    j<- i[ 2:1 ] # orthonormal
    
    
    ##### here is cramer #######
    
    newm = NULL
    a<- matrix( data = c( i,j ) , nrow = 2 )
    
    for ( k in 1:nrow( m ) ) {
      
      b<- as.matrix( c( m[ k , ] ) , ncol = 1 )
      
      newx<- ( a[ 2 , 2 ] * b[ 1 ] - b[ 2 ] * a[ 1 , 2 ] ) / ( a[ 1 , 1 ] * a[ 2 , 2 ] - a[ 2 , 1 ] * a[ 2 , 1 ] )
      newy<- ( a[ 1 , 1 ] * b[ 2 ] - b[ 1 ] * a[ 2 , 1 ] ) / ( a[ 1 , 1 ] * a[ 2 , 2 ] - a[ 2 , 1 ] * a[ 2 , 1 ] )
      
      newPoint<- c( newx , newy )
      newm<- rbind( newm , newPoint )
    }
    
    total_matrix<- rbind( total_matrix , newm )
  }
  
  
  ##### join all #######
  colnames( total_matrix )<-c( "nx" , "ny" )
  row.names( total_matrix )<- NULL
  df<- cbind( df[ 1:3 ] , total_matrix , df[ 4:length( df ) ] )
  
  ## wirte files ######
  
  dir.create(path.to.save,recursive = TRUE,showWarnings = FALSE)
  
  if ( save.parquet == TRUE & save.by.video == TRUE ) {
    
    require( arrow )
    
    file_names<- unique( df$name )
    
    for ( f in 1:length( file_names ) ) {
      
      bit_df<- df[ df$name == file_names[ f ] , ]
      
      write_parquet( x = bit_df , paste( path.to.save , "/" , file_names[f] , ".parquet" , sep = "" ) )
      
    } 
  } 
  
  
  if ( save.parquet == TRUE & save.by.video == FALSE ) {
    
    require( arrow )
    
    write_parquet( x = df , paste(path.to.save , "/" ,
                                  format(Sys.time() ) , "_" , 
                                  system( "whoami" , intern = TRUE ) ,
                                  ".parquet" , sep = "" ) )
    
  } 
  
  
  if ( save.csv == TRUE & save.by.video == TRUE ) {
    
    
    file_names<- unique( df$name )
    
    for ( f in 1:length( file_names ) ) {
      
      bit_df<- df[ df$name == file_names[ f ] , ]
      
      write.csv( x = bit_df, paste(path.to.save, "/" , file_names[f] , ".csv" , sep = "" ) , row.names = FALSE )
      
    }
  }  
  
  
  
  if ( save.csv == TRUE & save.by.video == FALSE ) {
    
    
    
    print( "Please write it as regular csv file, write.csv(filename) " )
    
  }  
  
  return( df )    
  
}





df<-dfMaker(input.folders =args$data.input,save.csv = F,return.empty = F,extra.var = TRUE, save.parquet = FALSE )

new_df<-cramerOpenPosev2(df = df, set.NAs = TRUE,save.parquet = args$parquet,path.to.save = args$path.save,save.by.video = args$all.in.file,save.csv = args$csv)

